# Use the official MySQL base image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=Apple@3005 \
    MYSQL_DATABASE=loginapp \
    MYSQL_USER=meghana \
    MYSQL_PASSWORD=Sujatha@3005

# Copy the SQL dump file into the Docker image for database initialization
COPY /home/ec2-user/project/data.sql /docker-entrypoint-initdb.d/

# Expose port 3306 for MySQL
EXPOSE 3306